spring:
  datasource:
    url: jdbc:mysql://localhost/vollmed_api
    username: yurir
    password: 123456
  application:
    name: api-rest
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true

server:
  port: 8080
  servlet:
    context-path: /crm-api
  error:
    include-stacktrace: never

app:
  security:
    token:
      client-secret: ${APP_CLIENT_SECRET:12345678}
