spring:
  datasource:
    url: jdbc:mysql://mysql:3306/vollmed_api
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: api-rest
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true

server:
  port: 8080
  servlet:
    context-path: /crm-api
  error:
    include-stacktrace: never

app:
  security:
    token:
      client-secret: ${APP_CLIENT_SECRET:12345678}

integrations:
  host:
    via-cep: ${VIA_VEP_HOST:https://viacep.com.br}
  context-path:
    via-cep: ${VIA_CEP_CONTEXT_PATH:/ws}
  enpoint:
    get-zip-code: ${GET_ZIPCODE:/{zipCode}/json}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

#Uncomment for explicit paths from swagger, see more: https://springdoc.org/
#springdoc:
#  swagger-ui:
#    path: /swagger-ui
#  api-docs:
#    path: /v3/api-docs