spring:
  datasource:
    url: jdbc:mysql://localhost/vollmed_api
    username: root
    password: '@Link123'
  application:
    name: api-rest
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true

server:
  port: 8080
  servlet:
    context-path: /crm-api

